### ISSUE TITLE
the code is unable to run..please help.

### ISSUE THREAD

**Issue by lnmishra122** [AbrahamSanders/seq2seq-chatbot#25]
runfile('C:/Users/BBNH/Desktop/chatbot2/chat.py', wdir='C:/Users/BBNH/Desktop/chatbot2')
Traceback (most recent call last):

  File "<ipython-input-1-21a3637c858f>", line 1, in <module>
    runfile('C:/Users/BBNH/Desktop/chatbot2/chat.py', wdir='C:/Users/BBNH/Desktop/chatbot2')

  File "C:\Users\BBNH\Anaconda3\envs\chatbot2\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\BBNH\Anaconda3\envs\chatbot2\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/BBNH/Desktop/chatbot2/chat.py", line 10, in <module>
    from chatbot_model import ChatbotModel

  File "C:\Users\BBNH\Desktop\chatbot2\chatbot_model.py", line 5, in <module>
    import tensorflow as tf

  File "C:\Users\BBNH\Anaconda3\envs\chatbot2\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import

  File "C:\Users\BBNH\Anaconda3\envs\chatbot2\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow

  File "C:\Users\BBNH\Anaconda3\envs\chatbot2\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "C:\Users\BBNH\Anaconda3\envs\chatbot2\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\BBNH\Anaconda3\envs\chatbot2\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\BBNH\Anaconda3\envs\chatbot2\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\BBNH\Anaconda3\envs\chatbot2\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\BBNH\Anaconda3\envs\chatbot2\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed with error code -1073741795

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by AbrahamSanders** [comment]
Hi @lnmishra122, how did you install tensorflow, and which version?
Also, how are you launching chat.py? (please provide the command).

It looks like there is some kind of internal issue loading the tensorflow native DLLs when executing
`import tensorflow as tf`

Maybe try re-installing tensorflow?

**Comment by lnmishra122** [comment]
Hii @Abraham, I used pip --upgrade command mentioned in your readme file.Previously i had tensorflow version 1.0.0 and it got upgraded to 1.14. I will solve the issue somehow but could would you tell me which version of tensorflow is best suited for this code to run. Thank you

**Comment by lnmishra122** [comment]
it worked i just had to install a different version of tensorflow . Thanks for you help.

**Comment by AbrahamSanders** [comment]
@lnmishra122 great, I'm glad it is working for you now!
