### ISSUE TITLE
    from tensorflow.contrib.tensorboard.plugins import projector ModuleNotFoundError: No module named 'tensorflow.contrib

### ISSUE THREAD

**Issue by asmaDur-01** [AbrahamSanders/seq2seq-chatbot#39]
Hi, 
I have this error
2022-07-18 11:26:12.383850: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-07-18 11:26:12.384185: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "chat.py", line 10, in <module>
    from chatbot_model import ChatbotModel
  File "C:\Users\winDows\seq2seq-chatbot\seq2seq-chatbot\chatbot_model.py", line 7, in <module>
    from tensorflow.contrib.tensorboard.plugins import projector
ModuleNotFoundError: No module named 'tensorflow.contrib'

**Comment by AbrahamSanders** [comment]
Hi @asmaDur-01, this was originally written for TF 1.x and does not work with current versions of TensorFlow. You can create an environment with the earlier version of TF, but I would encourage checking out more recent chatbot implementations based on Transformers. e.g., [DialoGPT](https://github.com/microsoft/DialoGPT)

Best,
Abraham

**Comment by asmaDur-01** [comment]
> Hi @asmaDur-01, this was originally written for TF 1.x and does not work with current versions of TensorFlow. You can create an environment with the earlier version of TF, but I would encourage checking out more recent chatbot implementations based on Transformers. e.g., [DialoGPT](https://github.com/microsoft/DialoGPT)
> 
> Best, Abraham

Okay , I will see
thanks for your response
